services:
  - type: web
    name: vigia-video
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: VIGIA_SUPABASE_URL
        value: https://epadzsrfsvckyjugcvpd.supabase.co
      - key: VIGIA_SUPABASE_PUBLISHABLE_KEY
        value: sb_publishable_PxFa4vMqovqCIDOwEsoiBQ_2q2jETc_
