/* VIGÍA · caps.js — matriz de capacidades mostrada en Administración (debe coincidir con CAPACIDADES.md)
 * v = implementado y verificado por prueba automática · p = implementado, verificación parcial/manual · f = fase posterior */
window.V.CAPACIDADES = [
  ['Inicio de sesión local, contraseñas aleatorias PBKDF2, selección de organización', 'v', 'Prueba «Autenticación». Bloqueo tras 5 intentos fallidos (60 s).'],
  ['Aislamiento multicliente en cada operación de la API interna', 'v', 'Prueba «Aislamiento»: 20+ accesos cruzados denegados. Aislamiento lógico: los datos viven en el navegador del equipo.'],
  ['Permisos por rol (5 roles, 20 permisos) aplicados en la API', 'v', 'Prueba «Permisos por rol».'],
  ['Cámaras, sedes, zonas, grupos, zona horaria IANA, zonas de exclusión', 'p', 'CRUD verificado en pruebas; editor de zonas probado manualmente.'],
  ['Importación MP4/MOV/WebM con validación de bytes, límite de tamaño y SHA-256', 'v', 'Original inmutable (no se puede sobrescribir) y verificable.'],
  ['Metadatos: duración, códec, resolución, fps, audio, hora del contenedor', 'v', 'Hora de captura: declarada > contenedor > desconocida. Nunca se deduce de la carga.'],
  ['Indexación asíncrona con progreso real, cola persistente y reanudación', 'v', 'Trabajador en el hilo principal con cesión cooperativa; un trabajo a la vez.'],
  ['Detector de movimiento determinista (movimiento-v1)', 'v', 'No clasifica objetos; así se declara en cada respuesta.'],
  ['Detector de objetos local COCO-SSD (TensorFlow.js), opcional y explícito', 'p', 'Verificado con persona real (foto NASA de dominio público) en el video sintético. Precisión en cámaras reales no medida.'],
  ['Fotograma auténtico a resolución nativa con hash', 'v', 'PNG sin pérdida desde la decodificación del navegador.'],
  ['Clip MP4 sin recodificar (copia de flujo) con límites reales y hash', 'v', 'Verificado también con ffprobe/ffmpeg en Node (H.264/AAC y VP9/Opus).'],
  ['Clip de WebM / MP4 fragmentado mediante MediaRecorder', 'p', 'Etiquetado como RECODIFICADO; tiempo real 1×.'],
  ['Chat en español con intérprete determinista y tarjeta de interpretación editable', 'v', '21 pruebas unitarias del intérprete + recorrido principal.'],
  ['Consultas de seguimiento («amplía cinco minutos antes», «ahora solo vehículos»)', 'v', ''],
  ['Cobertura, índice pendiente y respuestas honestas sin evidencia', 'v', 'Prueba «Respuestas honestas».'],
  ['Cámara web en vivo (getUserMedia) con edad del cuadro y búfer de 5 min', 'v', 'Probado con el dispositivo simulado de Chromium (primer cuadro ≈1,2 s). Con cámara física: requiere permiso del navegador.'],
  ['Emulación en vivo desde archivo (reloj simulado, etiquetada)', 'v', 'Prueba de interfaz: «ahora» devuelve cuadro, edad y etiqueta EMULACIÓN.'],
  ['Reglas temporales desde chat con confirmación, alertas en la aplicación', 'v', 'Prueba de interfaz: vista previa → confirmación → alerta por movimiento real. Sin notificaciones externas (por diseño).'],
  ['Expedientes: hipótesis / sugerido IA / revisado / confirmado, notas, aprobación', 'v', ''],
  ['Informe preliminar HTML y PDF con fuentes, hashes, método, lagunas', 'v', 'No afirma admisibilidad legal.'],
  ['Tablero de indicadores con totales reales', 'v', ''],
  ['Auditoría encadenada por hash y detección de alteraciones', 'v', ''],
  ['Retención configurable y protección de evidencia en expedientes', 'p', 'Borrado manual respeta protección; borrado programado: fase posterior.'],
  ['Nube Supabase: cuentas, organizaciones con RLS y sincronización de metadatos/custodia', 'p', 'Esquema y RLS verificados con SQL; sincronización probada con cliente simulado y validación del esquema. Los videos no se suben.'],
  ['Analítica: conteo de entradas/salidas por línea e ingreso en grupo', 'v', 'Video de casos: 4/1 esperados = 4/1 obtenidos; prueba unitaria del motor.'],
  ['Analítica: intrusión, merodeo, aglomeración y ocupación por zona', 'v', 'Verificado con IA real en el video de casos y en prueba unitaria.'],
  ['Analítica: vehículo mal estacionado', 'v', 'Moto en zona de no estacionar 45 s → 1 evento.'],
  ['Analítica: puerta abierta (sin IA)', 'v', '71% de cambio con la puerta abierta frente a 14% con una persona delante.'],
  ['Analítica: objeto abandonado y manipulación de cámara (sin IA)', 'v', 'Sin falsos positivos por vehículo estacionado, puerta, humo ni persona quieta en el video de casos.'],
  ['Analítica: búsqueda por color de prenda', 'p', 'Funciona en el video de casos (retratos); falta validar con cuerpos completos en cámaras reales.'],
  ['Analítica: posible humo', 'p', 'EXPERIMENTAL y advertido en cada respuesta; no reemplaza detectores certificados.'],
  ['Analítica en vivo con reglas y alertas (puerta, merodeo, intrusión, etc.)', 'p', 'Motor en cada cuadro en vivo; alertas por regla. Probado con emulación en la prueba de interfaz.'],
  ['Conexión RTSP', 'f', 'Un navegador no abre RTSP: requiere agente de borde (ARCHITECTURE.md).'],
  ['Servidor multiusuario (FastAPI + PostgreSQL + cola distribuida)', 'f', 'Diseñado en ARCHITECTURE.md / API.md; esta entrega es la edición local.'],
  ['Búsqueda semántica con embeddings visuales', 'f', 'No implementada: no se ofrece en la interfaz.'],
  ['Reconocimiento facial, biometría, lectura de placas', 'f', 'Excluidos por defecto; sujetos a evaluación legal y de precisión.'],
  ['Escala a 5.000 cámaras', 'f', 'Objetivo de diseño; no validado. Ver ARCHITECTURE.md.']
];
